drivers: Fix strict-prototypes warnings from Clang
../drivers/thermal/msm_thermal-dev.c:412:31: error: a function
declaration without a prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
  412 | void msm_thermal_ioctl_cleanup()                      |				       ^
      |                               void
1 error generated.

Signed-off-by: Linhui Liu <liulinhui36@gmail.com>